### ISSUE TITLE
Windows 10 issues

### ISSUE THREAD

**Issue by testemright** [saveenr/Fix_My_Pen#1]
For the life of me, I can't get anything to work on windows 10.

**Comment by saveenr** [comment]
Hi testemright, due to changes to the pen subsystem in Windows 8 and later versions, this tool only works for Windows 7.

For Windows 8 and 10, see this page for instructions that may help (and that don't require this tool): http://viziblr.com/news/2013/6/23/the-windows-and-wacom-tablet-nightmare-is-over.html
